### ISSUE TITLE
[Task] Automated rules do not automatically start on targets that need authentication

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1041]
1. Have an automated rule with `matchExpression==true` already locally in `cryostat/conf/rules`, either created manually or created through cryostat AutomatedRuleCreation UI, and DON'T have JMX credentials for the target we are testing (in this case cryostat:9091)
e,g,
```{"name":"dfgh","description":"","matchExpression":"true","eventSpecifier":"template=Continuous,type=CUSTOM","archivalPeriodSeconds":0,"initialDelaySeconds":0,"preservedArchives":0,"maxAgeSeconds":0,"maxSizeBytes":0}```
2. Run `CRYOSTAT_DISABLE_SSL=true CRYOSTAT_CORS_ORIGIN=http://localhost:9000 sh smoketest.sh` and `web-client`
3. Notice that before or after authenticating target `io.cryostat.Cryostat (service:jmx:rmi:///jndi/rmi://cryostat:9091/jmxrmi)`  automated rules aren't run on it. `(with user: smoketest, password: smoketest)`

Notice that if you already had JMX credentials set for this target, automated rules are correctly started on application startup.

**Comment by maxcao13** [comment]
This happens because the `RuleProcessor` automatically starts rules based on `TargetJvmDiscovery` `FOUND` notifications and tries to establish a connection to the found target. However, the connection cannot be established because of authentication or untrusted SSL so rule recordings are never started even after auth since a new `TargetJvmDiscovery` notification was not emitted again. 

To fix this, would it make sense to start a new thread which waits to be connected to the unconnectable target, and when it does, sends a new event for the recording to start?

**Comment by andrewazores** [comment]
In the case of target SSL not being trusted there are two solutions:

1. Redeploy the target with a trusted SSL cert. This means the target will disappear and then reappear as a connectable target, so the Automated Rule will successfully activate.
2. Add the SSL cert so Cryostat trusts it. This requires restarting the Cryostat JVM, and in this next lifecycle the connectable target will be discovered and the Automated Rule will successfully activate.

For the case where the target is not connectable because it requires JMX auth credentials and we have none or have invalid ones stored, I think this could be solved by internally implemented a third kind of event listener on the rule processor so that it is aware of when JMX credentials are changed, much like how it is aware of when targets appear/disappear or rule definitions are created/deleted. When a JMX credential is added or removed we can test which targets that credential applied to and check if that set has a nonempty intersection with the targets matched by each of our rule definitions. If we have changed credentials for any targets then we should retry rule activation on them.

**Comment by lkonno** [comment]
When the JMX credential is removed, should it have to deactivate the rules from the target?

**Comment by andrewazores** [comment]
Good question. I don't think so, the user should probably explicitly delete the rule definition in that case. Since both of those use match expressions it's not guaranteed that the credential being removed maps 1:1 to any particular rule's matched targets though. If we stop the recording pre-emptively when credentials are removed we may inadvertently lose JFR data that has not yet been copied into archives so I'd rather err on the side of caution any recordings be so the user still has a chance to recover them later.
