### ISSUE TITLE
[Story] Add pull-request and issue templates to Cryostat repositories

### ISSUE THREAD

**Issue by maxcao13** [cryostatio/cryostat#1269]
Add PR and issue templates across cryostat repositories

- [x] - https://github.com/cryostatio/cryostat/issues/1268
- [x] - https://github.com/cryostatio/cryostat-web/issues/677
- [x] cryostatio/cryostat-operator#553
- [x] cryostatio/cryostat-helm#54

**Comment by andrewazores** [comment]
I suppose all the repos should have similar templates, but I think the three you've listed plus `-helm` are the four that are most likely to have external contributions.

The PR labelling with `needs-triage` will be a little different for this repo compared to some of the others since it has a split CI for PRs vs pushes to `main`. Issue templates will be largely the same across every repo I think.
