### ISSUE TITLE
[Request] Updated credentials and rules endpoints

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat#1386]
## Describe the feature

In order to support viewing `related resources` for each target in topology view, we need some endpoint that conveniently returns the required information.

- [ ] A credential endpoint that also returns the array of matching targets [1]
- [ ] A rule endpoint that does the same as [1]
- [ ] A credential endpoint that takes a credential and a target and check if the target is matched [2]
- [ ] A rule endpoint that does the same as [2]

**Comment by andrewazores** [comment]
>  A credential endpoint that takes a credential and a target and check if the target is matched [2]

If the credential and the target are both ones that were retrieved from the backend already, ie not ones that the user is currently in the process of creating, then this can just be done on the frontend. The reason why is that if they have been retrieved from the backend then they have already gone through the backend's validation processes, ie. the matchExpression of the credential has gone through the full parsing and sanitization. In the other conversation where I said we should not port the matchExpression validation/evaluation to the frontend I should have clarified that. It's fine for the frontend to simply evaluate a retrieved expression against the list of targets that it has also just queried for. This is essentially already happening when you ex. create an Automated Rule and type in the matchExpression and get immediate feedback about whether the expression is valid and whether it matches the selected target - this is the frontend evaluating the expression against the target. But, in the end that rule still gets submitted to the backend and the expression is fully validated there to ensure it doesn't contain any illegal syntax like function definitions or other control flow.

>  A credential endpoint that also returns the array of matching targets [1]
> A rule endpoint that does the same as [1]

If there was an endpoint that took a matchExpression and evaluated it on the server side, returning the list of matching targets, this would also meet the criteria for both of these, right? It would also be extensible into an expression validation call that the frontend can use to replace or complement the client-side evaluation I talked about above, if the request also took an optional target parameter (or list of targets parameter).

Something like:

```
request:
POST /api/beta/matchExpressions
matchExpression: "target.alias == 'mytarget'"

response:
/api/beta/matchExpression/1
{ "matchExpression": "target.alias == 'mytarget'" }
```

```
request:
DELETE /api/beta/matchExpressions/1

response:
OK
```

```
request:
GET /api/beta/matchExpressions/1

response:
{ "matchExpression": "target.alias == 'mytarget'" }
```


```
request:
GET /api/beta/matchExpressions/1?matches=true

response:
{
  "matchExpression": "target.alias == 'mytarget'",
  "matches": [
    { ... },
    { ... }
  ]
}
```

```
request:
POST /api/beta/matchExpressions?matches=true&dryrun=true
matchExpression: "target.alias == 'mytarget'"

response:
{
  "matchExpression": "target.alias == 'mytarget'",
  "matches": [
    { ... },
    { ... }
  ]
}
```

```
request:
POST /api/beta/matchExpressions?matches=true&dryrun=true
matchExpression: "target.alias == 'mytarget'"
targets: [{ 1... }, { 2... }]

response:
{
  "matchExpression": "target.alias == 'mytarget'",
  "matches": [
    { 2... }
  ]
}
```

```
request:
POST /api/beta/matchExpressions?matches=true&dryrun=false
matchExpression: "target.alias == 'mytarget'"
targets: [{ 1... }, { 2... }]

response:
HTTP 400
```

I also mentioned somewhere before that I think creating matchExpressions as a top-level resource in their own right made sense since they are used in two places now (credentials and rules) and could be used in more in the future, so this is an opportunity to start moving in that direction.
