### ISSUE TITLE
[Bug] CI startup failure

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#1755]
### Current Behavior

```
Invalid workflow file: .github/workflows/push-ci.yml#L34
The workflow is not valid. .github/workflows/push-ci.yml (Line: 34, Col: 20): Invalid input, skip-itests is not defined in the referenced workflow.
```

### Expected Behavior

CI run on push-to-main should be able to run and pass as normal.

### Environment

```Markdown
Since #1683
```

### Anything else?

![image](https://github.com/cryostatio/cryostat/assets/3787464/da55cbd0-8b7c-4f88-9be1-f8a8a792aae4)

**Comment by andrewazores** [comment]
![image](https://github.com/cryostatio/cryostat/assets/3787464/a7c0f917-7959-4e6c-bc7d-4f50aae9a264)

```
Run redhat-actions/podman-login@v1
Error: Error: Input required and not supplied: username
```

**Comment by aali309** [comment]
> ![image](https://user-images.githubusercontent.com/3787464/279118729-a7c0f917-7959-4e6c-bc7d-4f50aae9a264.png)
> 
> ```
> Run redhat-actions/podman-login@v1
> Error: Error: Input required and not supplied: username
> ```

I have no clue why it is saying `username` not supplied when it supplied on `ci-build-image.yml` file

**Comment by tthvo** [comment]
I think the argument to the line below is empty since it is a push event, not a comment event:

https://github.com/cryostatio/cryostat/blob/d33cc44ea19274b3cedddee32846250d6f881a57/.github/workflows/ci-build-image.yml#L71

**Comment by andrewazores** [comment]
Looks right. @aali309 I'm looking at that `build-image` step again and I'm still not sure I see why exactly the `podman-login` action is required. Which subsequent step in that workflow is interacting with `ghcr.io`? And why would it need to use a commenting user's username as the login while using the `secrets.GITHUB_TOKEN` as the password?

Can we try just removing the `podman-login` step and see if anything actually breaks?

**Comment by aali309** [comment]
yes when I remove the `podman-login` 

![image](https://github.com/cryostatio/cryostat/assets/56743004/1f35fd06-8ee1-4471-a590-74ee74647bb4)

workflow LINK: [https://github.com/aali309/cryostat/actions/runs/6700548654/job/18206670997](https://github.com/aali309/cryostat/actions/runs/6700548654/job/18206670997)

**Comment by andrewazores** [comment]
Okay, so removing the `podman-login` looks OK then. Now it's failing on downloading from the GH Packages Maven repository, so there needs to be some setup with `maven-settings` ie. `~/.m2/settings.xml`.

**Comment by aali309** [comment]
with `podman login`

`/build_test` LINK: [https://github.com/aali309/cryostat/actions/runs/6700846180](https://github.com/aali309/cryostat/actions/runs/6700846180)

![image](https://github.com/cryostatio/cryostat/assets/56743004/f4e262c7-9f19-4d1b-9261-705da228db50)

`retest` LINK: [https://github.com/aali309/cryostat/actions/runs/6700928824](https://github.com/aali309/cryostat/actions/runs/6700928824)

![image](https://github.com/cryostatio/cryostat/assets/56743004/daffeeea-f2dd-45f4-968e-c73b6b236b98)

 
Push to quay fails is expected to fail I assume because of the access restrictions (i.e username+password).
push-ci workflow LINK: [https://github.com/aali309/cryostat/actions/runs/6700718429](https://github.com/aali309/cryostat/actions/runs/6700718429)
![image](https://github.com/cryostatio/cryostat/assets/56743004/604e2805-883b-4e8b-af2a-6b5ad0146874)

**Comment by aali309** [comment]
> Okay, so removing the `podman-login` looks OK then. Now it's failing on downloading from the GH Packages Maven repository, so there needs to be some setup with `maven-settings` ie. `~/.m2/settings.xml`.

I will try this option tomorrow morning
