### ISSUE TITLE
[Request] Add more sample applications to smoketest

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#403]
### Describe the feature

More sample applications, in particular examples of real applications (not Quarkus hello-worlds and the vertx-fib-demo) would be good to have in the smoketest scenario for testing.

**Comment by tthvo** [comment]
> I am thinking the smoketest script can categorize the types of sample apps. For example, basic, basic-with-agent, search, etc. Then, we can run bash smoketest -t basic,search.

This is a good idea, since running all of the sample apps ends up taking more and more resources on the workstation (and more time to pull and start containers) and may not always be desired. But `-t` alone, or `-t all`, should still be available so we can run everything at once to provide a full test suite without having to restart the smoketest to test against different things.

_Originally posted by @andrewazores in https://github.com/cryostatio/cryostat/issues/570#issuecomment-2239445865_

Putting the idea here to track :D

**Comment by andrewazores** [comment]
^ working on that now.
