### ISSUE TITLE
Some unit test failures are unreported, or tests do not run

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#502]
Some unit tests are evidently not run by Maven failsafe and/or JUnit or for some other reason and are observed to be failing when run manually. @hareetd could you document these specific failures here since you have the first-hand report data?

Maybe relevant: https://stackoverflow.com/questions/3365628/junit-tests-pass-in-eclipse-but-fail-in-maven-surefire

**Comment by hareetd** [comment]
There are certain unit tests which test exception throwing for invalid recording options by passing in `null` values using a `Map` but cause a `java.lang.NullPointerException` instead of the expected `HttpStatusException`. 

Specifically, the tests are:

1. https://github.com/cryostatio/cryostat/blob/main/src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingsPostHandlerTest.java#L314

2. https://github.com/cryostatio/cryostat/blob/main/src/test/java/io/cryostat/net/web/http/api/v1/TargetRecordingOptionsPatchHandlerTest.java#L155
