### ISSUE TITLE
[Bug] "About" and "Homepage" are not set on the new repo 

### ISSUE THREAD

**Issue by ahus1** [cryostatio/cryostat#552]
### Current Behavior

The new repo misses that information: 

![image](https://github.com/cryostatio/cryostat/assets/3957921/586d51b4-79b8-4428-a8c1-4053d7a868ff)

### Expected Behavior

The old repo has this set up correctly: 

![image](https://github.com/cryostatio/cryostat/assets/3957921/9f1c11a9-e33a-419a-8a4e-c5e71e105539)

### Steps To Reproduce

See screenshots above. 

### Environment

```Markdown
n/a
```

### Anything else?

BTW, by changing the repo, you're missing out on all people who subscribed or starred your old repo!

**Comment by andrewazores** [comment]
> The new repo misses that information:

Thanks for catching that, I've updated it now!

> BTW, by changing the repo, you're missing out on all people who subscribed or starred your old repo!

I know, it's a really unfortunate side-effect. This happened because I had already started on early prototyping of what has become 3.0 back around the 2.3 timeframe, so 3.0 and 2.4 were in development concurrently as totally separate codebases with no real shared git history, and only some copy-pasted and adjusted code in common. It also wasn't clear at that time what the release timing would be, or if the old repo would produce a 2.5 as well, so they were kept separated. In the end it felt wrong to overwrite all of the code from the old repo with the new repo and make the git history impossible to navigate.

Renaming the repositories this way so that old links continue to redirect to the new repo, plus adding some pointers in the old repo README and Discussions to this new one, seemed like a way to preserve the history while also hopefully make users aware of the change over.

**Comment by ahus1** [comment]
Thank you for adding this information. You might consider this issue now resolved. 

The feature you might have been looking for are orphaned branches which allows you to create branches in a single repository that don't share a common history. I used that in the past to create for example a separate branch for the old-style GitHub pages feature. Still, with the renaming of the repositories already done, this might no longer apply here. 

Again, consider closing this issue as resolved.
