### ISSUE TITLE
Platform auth managers should have tailored messages for users

### ISSUE THREAD

**Issue by andrewazores** [cryostatio/cryostat#87]
See rh-jmc-team/container-jfr-web#23

**Comment by tabjy** [comment]
I'm wondering what's the best way of telling if it's an OpenShift deployment on the server-side, currently, I came up with the following:
- in `WebServer`,  check the injected `AuthManager` is a `OpenShiftPlatformClient.OpenShiftAuthManager`, but the latter is not visible from there
- in `WebServer`, inject the `PlatformClient` and check if it's an `OpenShiftPlatformClient`, but the latter is not visible from there, or
- in `WebServer`, check `new OpenShiftPlatformStrategy(logger, env, resolver).isAvailable()`, but the latter is not visible from there

Could you please elaborate on how you want this implemented without breaking these abstractions.

**Comment by andrewazores** [comment]
The WebServer shouldn't care if it's an OpenShift instance in particular, there just needs to be a platform-specific help message that can be provided to the frontend for display. I haven't thought too deeply on this yet but my first idea here would be to add some method like `Map<String, String> getDocumentationMessages(String locale)` to the AuthManager interface. And add some WebServer endpoint that returns messages out of this map from its injected AuthManager instance for the given locale and key. The WebServer should not be doing any kind of instanceof type checking, nor should it need to know about any platform strategies or AuthManager implementations. The frontend client can then make a request to the backend to populate the auth token dialog with a string provided by the platform-specific AuthManager messages.

**Comment by tabjy** [comment]
Thank you for the elaboration. I now see the idea.

Just pointing out another possibility: rather than returning an empty 401 response on `/auth` failed, there could be an error message in the response body, potentially localized according to the request's `Accept-Language` header. `AuthManager`s can either throw an error with a localized message some-how contained or have a `String getDocumentationMessage(String key, String locale)` interface.

This reminds the lack of proper error handling and i18n for web service endpoints. At this time, we don't have a well-defined error response format for the client. (When implementing #90, I made the `failureHandler` returns a JSONify JavaScript `Error` Object for the sake of simplicity.)
